# pytest.ini
[pytest]
# Tu definujeme, kde má Pytest hľadať testy (test files)
python_files = test_*.py

# Tu definujeme cesty, ktoré má pridať do hľadania modulov (paths)
# Súčasný priečinok '.' znamená, že Pytest bude hľadať moduly v aktuálnom priečinku
pythonpath = .